import { LOCALES_ACTIONS } from "../../shared/redux/actions.constants";

export const CALLS_ACTIONS = {
  CALL_LOAD_LIST: "CALL_LOAD_LIST",
  CALL_LOAD_LIST_DONE: "CALL_LOAD_LIST_DONE",
  CALLS_ARCHIVE_CALL: "CALLS_ARCHIVE_CALL",
  CALLS_UPDATE_CHECKLIST: "CALLS_UPDATE_CHECKLIST",
}
